import express from 'express';
import Appointment from '../models/Appointment.js';
import Expense from '../models/Expense.js';
import User from '../models/User.js';
import { protect, authorizeRoles } from '../middleware/auth.js';

const router = express.Router();

// @desc    Get dashboard analytics data
// @route   GET /api/finance/analytics
// @access  Private (Owner, Manager, Admin)
router.get('/analytics', protect, authorizeRoles('owner', 'manager', 'admin'), async (req, res) => {
  try {
    const todayStr = new Date().toISOString().split('T')[0];
    const today = new Date();
    
    // Get all appointments and expenses
    const appointments = await Appointment.find({});
    const expenses = await Expense.find({});
    const employees = await User.find({});

    // Filter completed appointments for revenue calculations
    const completedAppts = appointments.filter(a => a.status === 'completed');

    // 1. Today's Customers & Today's Revenue
    const todayCompletedAppts = completedAppts.filter(a => a.date === todayStr);
    const todayCustomers = todayCompletedAppts.length;
    const todayRevenue = todayCompletedAppts.reduce((sum, a) => sum + a.price, 0);

    // 2. Helper to get start and end dates of intervals
    const getDaysAgo = (days) => {
      const d = new Date(today);
      d.setDate(today.getDate() - days);
      return d;
    };

    const sevenDaysAgoStr = getDaysAgo(7).toISOString().split('T')[0];
    const thirtyDaysAgoStr = getDaysAgo(30).toISOString().split('T')[0];
    const startOfYearStr = `${today.getFullYear()}-01-01`;

    // 3. Interval revenues
    const weeklyRevenue = completedAppts
      .filter(a => a.date >= sevenDaysAgoStr && a.date <= todayStr)
      .reduce((sum, a) => sum + a.price, 0);

    const monthlyRevenue = completedAppts
      .filter(a => a.date >= thirtyDaysAgoStr && a.date <= todayStr)
      .reduce((sum, a) => sum + a.price, 0);

    const yearlyRevenue = completedAppts
      .filter(a => a.date >= startOfYearStr && a.date <= todayStr)
      .reduce((sum, a) => sum + a.price, 0);

    // 4. Total Expenses & Profit
    const totalExpenses = expenses.reduce((sum, e) => sum + e.amount, 0);
    const totalProfit = yearlyRevenue - totalExpenses; // Profit based on current calendar year

    // 5. Popular Services Analytics
    const serviceCounts = {};
    completedAppts.forEach(a => {
      serviceCounts[a.serviceName] = (serviceCounts[a.serviceName] || 0) + 1;
    });
    const popularServices = Object.keys(serviceCounts).map(name => ({
      name,
      value: serviceCounts[name]
    })).sort((a, b) => b.value - a.value).slice(0, 5);

    // 6. Best Performing Barbers (Revenue generated by each)
    const barberRevenue = {};
    completedAppts.forEach(a => {
      barberRevenue[a.barberName] = (barberRevenue[a.barberName] || 0) + a.price;
    });
    const bestBarbers = Object.keys(barberRevenue).map(name => ({
      name,
      revenue: barberRevenue[name]
    })).sort((a, b) => b.revenue - a.revenue);

    // 7. Monthly Revenue Growth Stats (Past 6 months)
    const monthlySummary = {};
    // Seed past 6 months to make sure they appear even with no revenue
    for (let i = 5; i >= 0; i--) {
      const d = new Date(today.getFullYear(), today.getMonth() - i, 1);
      const key = d.toLocaleString('default', { month: 'short', year: '2-digit' });
      monthlySummary[key] = { name: key, Revenue: 0, Expenses: 0, Profit: 0 };
    }

    // Accumulate revenues
    completedAppts.forEach(a => {
      const apptDate = new Date(a.date);
      const key = apptDate.toLocaleString('default', { month: 'short', year: '2-digit' });
      if (monthlySummary[key]) {
        monthlySummary[key].Revenue += a.price;
      }
    });

    // Accumulate expenses
    expenses.forEach(e => {
      const expDate = new Date(e.date);
      const key = expDate.toLocaleString('default', { month: 'short', year: '2-digit' });
      if (monthlySummary[key]) {
        monthlySummary[key].Expenses += e.amount;
      }
    });

    // Calculate profits
    const chartData = Object.values(monthlySummary).map(m => ({
      ...m,
      Profit: m.Revenue - m.Expenses
    }));

    // 8. Staff performance details (barbers with rating, experience, revenue, and bookings count)
    const staffSummary = employees.filter(e => e.role === 'barber').map(barber => {
      const barberAppts = completedAppts.filter(a => a.barberId === barber._id.toString());
      const revenue = barberAppts.reduce((sum, a) => sum + a.price, 0);
      return {
        _id: barber._id,
        name: barber.name,
        specialties: barber.specialties,
        rating: barber.rating || 5.0,
        experience: barber.experience || 0,
        avatar: barber.avatar,
        revenue,
        bookingsCount: barberAppts.length
      };
    });

    res.json({
      success: true,
      analytics: {
        todayCustomers,
        todayRevenue,
        weeklyRevenue,
        monthlyRevenue,
        yearlyRevenue,
        totalExpenses,
        totalProfit,
        popularServices,
        bestBarbers,
        chartData,
        staffSummary
      }
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

// @desc    Get all expenses
// @route   GET /api/finance/expenses
// @access  Private (Owner or Manager)
router.get('/expenses', protect, authorizeRoles('owner', 'manager'), async (req, res) => {
  try {
    const expenses = await Expense.find({});
    // Sort expenses by date descending
    expenses.sort((a, b) => b.date.localeCompare(a.date));
    res.json({ success: true, expenses });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

// @desc    Log a new expense
// @route   POST /api/finance/expenses
// @access  Private (Owner or Manager)
router.post('/expenses', protect, authorizeRoles('owner', 'manager'), async (req, res) => {
  const { category, amount, description, date } = req.body;

  if (!category || !amount || !date) {
    return res.status(400).json({ success: false, message: 'Please provide category, amount, and date' });
  }

  try {
    const expense = await Expense.create({
      category,
      amount: Number(amount),
      description: description || '',
      date
    });
    res.status(201).json({ success: true, message: 'Expense logged successfully', expense });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

export default router;
